name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npx pnpm i

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: eartharoid

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update sponsors"
          add: "sponsorkit/sponsors*"
          default_author: github_actions