name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 */2 * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: corepack enable && pnpm i

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: eartharoid
          SPONSORKIT_PATREON_TOKEN: ${{ secrets.SPONSORKIT_PATREON_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update sponsors"
          add: "sponsorkit/sponsors*"
          default_author: github_actions
